### ISSUE TITLE
tokens.json format in readme

### ISSUE THREAD

**Issue by worldpotato** [rootmos/twitch-cli#1]
Hi,

I want to ask you if you could describe how to use the tokens.json properly.

I want to try your twitch-cli but always get this traceback when executing `./twitch-cli chat <username>`:
```
Traceback (most recent call last):
  File "/home/worldpotato/repos/used_programms/twitch-cli/./twitch-cli", line 1424, in <module>
    c = Client(token=Client.fetch_token(scopes=scopes, token_path=args.token_path), cache=cache)
  File "/home/worldpotato/repos/used_programms/twitch-cli/./twitch-cli", line 253, in fetch_token
    with token_path.open() as f: s = json.loads(f.read())
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by spezifisch** [comment]
Here is an example of a `tokens.json` with redacted tokens:
```json
{
  "user_follows_edit": "asdfdsfasdfadsf3452345sfasfd",
  "chat:edit chat:read": "dfdsfasdfadsf3452345sfasfd",
  "chat:read": "fdsfasdfadsf3452345sfasfd",
  "": "qewrewrqwre234rewqwer34234"
}
```

The keys are just the requested permission scopes separated by spaces. Only the needed permissions are requested for each command, eg. `twitch-cli chat <username> --read-only` will use the entry `chat:read` while without specifying `--read-only` the entry `chat:edit chat:read` will be used because you also need the chat write permission. It's kind of redundant but that's the current state.

The values are the tokens that you get after authorizing the script inside the browser to access your Twitch account.

Your exception message looks like the file `~/.twitch-cli/tokens.json` is either empty or contains garbage. Deleting it and running `twitch-cli` again should fix it.
